# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e6ee3f27d3260707bdf828ecfe573b79480e37ce9fd42b3aa263b2d2bcb2967a2e489b3cc80fbc5ad4003cf6b11a4bc070768b302211b4f0449e1bc66b2e2f9

test:
  secret_key_base: b32bda6937d5821ff144428a6595f264f6b6ed29d49bbd66d097807e7fa20a54a027d7345cbbdae21bfd3cb1ac2264c205e20d1a53e58b60c142fbd7cd57a573

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
